repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use latest stable version
    hooks:
      - id: flake8
        additional_dependencies: []  # e.g. ["flake8-bugbear"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3
